version: '3.0'

services:
  frontend:
    container_name: frontend 
    build:
      context: ./public/
      dockerfile: Dockerfile
    ports:
      - 80:80
  
  backend:
    container_name: backend
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000


networks:
  default:
    external:
      name: mern-stack