version: "3"
services:
  server:
    image: pankaj349/multi-server
    mem_limit: 128M
    hostname: api
    environment:
      - REDIS_HOST= $REDIS_HOST
      - REDIS_PORT= $REDIS_PORT
      - PGUSER= $PGUSER
      - PGHOST= $PGHOST
      - PGDATABASE= $PGDATABASE
      - PGPASSWORD= $PGPASSWORD
      - PGPORT= $PGPORT 
  client:
    image: pankaj349/multi-client
    mem_limit: 128M
    hostname: client
  worker:
    image: pankaj349/multi-worker
    mem_limit: 128M
    hostname: worker
    environment:
      - REDIS_HOST= $REDIS_HOST 
      - REDIS_PORT= $REDIS_PORT
  ngnix:
    image: pankaj349/multi-ngnix
    mem_limit: 128M
    hostname: worker
    ports:
      - '80:80'   