sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pankaj/reactimage:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true pankaj/reactimage:latest npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: Docker-React
  env: Dockerreact-env-1
  bucket-name: elasticbeanstalk-ap-south-1-008610611601
  bucket-path: Docker-React
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY